version: '3.8'
services:
  movies:
    image: rajeshanagani/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: rajeshanagani/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
   dth:
    image: rajeshanagani/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: rajeshanagani/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

